### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alphafox02** [racerxdl/lms_tcp#1]
No issue, more of just a request for info. This sounds great and I’d love to try it this week with a LimeSDR mini. I’m not super familiar with go. Would you have any docs or recommendations for setup? I’ve looked over some of the files and it seems to mention prerequisites.

**Comment by racerxdl** [comment]
Hey @alphafox02 , yeah I forgot to add the docs to the readme.

Well you only need the latest golang version and limesuite installed. Then you can run:

```bash
go install github.com/racerxdl/lms_tcp/cmd
```

which should put the binary at $GOROOT/bin

I will setup some documentation and CI to auto-build / release binaries as well ^^


- In the usage, is basically the same as rtl_tcp with a few new options:

* `-lpf [Hz]` - sets the analog frontend Low Pass Filter 
* `-ov [N]` - sets the oversampling factor. The value of `0` is "max as possible" for the specified sample rate. This is done in FPGA side (so no CPU usage penalty)
* `-antennaName [NAME]` - the antenna to use. Defaults to `LNAL`

**Comment by alphafox02** [comment]
Awesome, greatly appreciated. Would you happen to know if you can run this without a desktop? I’ve never actually tried to run the LimeSDR just from the command line and wasn’t sure if linesuite needed a full desktop installed or that’d just be needed for the GUI portion.

**Comment by racerxdl** [comment]
Yes, that application is command line only. liblimesuite doesn't need a GUI (you only need libLimeSuite)

**Comment by alphafox02** [comment]
Can’t wait to try. I’ll close this out and look forward to any enhancements you add.
